spring：
  profiles：
    active：
      - dev
---
server:
  port: 8003
spring:
  application:
    name: MICRO-SERVER-DEV
  profiles: dec  # 这是一个开发环境

---
server:
  port: 3356
spring:
  application:
    name: MICRO-SERVER-TEST
  profiles: test  # 测试环境
